runtime: python37

# Use gunicorn for serving
entrypoint: gunicorn -b :$PORT main:app

# Force https
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# Use the most puny system
instance_class: F1
resources:
  cpu: 1
  memory_gb: 0.256
  disk_size_gb: 10

# manual_scaling:
#   instances: 1
automatic_scaling:
  min_instances: 0
  max_instances: 1
